library(tidyverse)

lionRGB <- read.csv("../ImageCSV/lionCSV.csv")
lionBlue <- slice(lionRGB, 1:256)
lionGreen <- slice(lionRGB, (1+256):(256+256))
lionRed <- slice(lionRGB, (1+256*2):(256+256*2))

x <- 1:256
plot(x, lionRed$R3C3)

birdRGB <- read.csv("../ImageCSV/birdCSV.csv")
birdBlue <- slice(birdRGB, 1:256)
birdGreen <- slice(birdRGB, (1+256):(256+256))
birdRed <- slice(birdRGB, (1+256*2):(256+256*2))

#plot blue of bird
plot(x, birdBlue$R0C0)
plot(x, birdBlue$R0C1)
plot(x, birdBlue$R0C2)
plot(x, birdBlue$R0C3)
plot(x, birdBlue$R0C4)
plot(x, birdBlue$R1C0)
plot(x, birdBlue$R1C1)
plot(x, birdBlue$R1C2)
plot(x, birdBlue$R1C3)
plot(x, birdBlue$R1C4)
plot(x, birdBlue$R2C0)
plot(x, birdBlue$R2C1)
plot(x, birdBlue$R2C2)
plot(x, birdBlue$R2C3)
plot(x, birdBlue$R2C4)
plot(x, birdBlue$R3C0)
plot(x, birdBlue$R3C1)
plot(x, birdBlue$R3C2)
plot(x, birdBlue$R3C3)
plot(x, birdBlue$R3C4)
plot(x, birdBlue$R4C0)
plot(x, birdBlue$R4C1)
plot(x, birdBlue$R4C2)
plot(x, birdBlue$R4C3)
plot(x, birdBlue$R4C4)

# plot red of bird
plot(x, birdRed$R0C0)
plot(x, birdRed$R0C1)
plot(x, birdRed$R0C2)
plot(x, birdRed$R0C3)
plot(x, birdRed$R0C4)
plot(x, birdRed$R1C0)
plot(x, birdRed$R1C1)
plot(x, birdRed$R1C2)
plot(x, birdRed$R1C3)
plot(x, birdRed$R1C4)
plot(x, birdRed$R2C0)
plot(x, birdRed$R2C1)
plot(x, birdRed$R2C2)
plot(x, birdRed$R2C3)
plot(x, birdRed$R2C4)
plot(x, birdRed$R3C0)
plot(x, birdRed$R3C1)
plot(x, birdRed$R3C2)
plot(x, birdRed$R3C3)
plot(x, birdRed$R3C4)
plot(x, birdRed$R4C0)
plot(x, birdRed$R4C1)
plot(x, birdRed$R4C2)
plot(x, birdRed$R4C3)
plot(x, birdRed$R4C4)

# plot green of bird
plot(x, birdGreen$R0C0)
plot(x, birdGreen$R0C1)
plot(x, birdGreen$R0C2)
plot(x, birdGreen$R0C3)
plot(x, birdGreen$R0C4)
plot(x, birdGreen$R1C0)
plot(x, birdGreen$R1C1)
plot(x, birdGreen$R1C2)
plot(x, birdGreen$R1C3)
plot(x, birdGreen$R1C4)
plot(x, birdGreen$R2C0)
plot(x, birdGreen$R2C1)
plot(x, birdGreen$R2C2)
plot(x, birdGreen$R2C3)
plot(x, birdGreen$R2C4)
plot(x, birdGreen$R3C0)
plot(x, birdGreen$R3C1)
plot(x, birdGreen$R3C2)
plot(x, birdGreen$R3C3)
plot(x, birdGreen$R3C4)
plot(x, birdGreen$R4C0)
plot(x, birdGreen$R4C1)
plot(x, birdGreen$R4C2)
plot(x, birdGreen$R4C3)
plot(x, birdGreen$R4C4)



